#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2023 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 0.32.0
# Product:       sen68
# Model-Version: 1.0.0
#

import pytest
from sensirion_i2c_sen68.device import Sen68Device


@pytest.fixture
def sensor(channel_provider):
    channel_provider.i2c_frequency = 100e3
    channel_provider.supply_voltage = 3.3
    with channel_provider:
        channel = channel_provider.get_channel(slave_address=0x6B,
                                               crc_parameters=(8, 0x31, 0xff, 0x0))
        yield Sen68Device(channel)


def test_get_product_name1(sensor):
    product_name = sensor.get_product_name()
    print(f"product_name: {product_name}; "
          )


def test_get_serial_number1(sensor):
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )


def test_get_version1(sensor):
    (firmware_major, firmware_minor, firmware_debug, hardware_major, hardware_minor, protocol_major, protocol_minor,
     padding
     ) = sensor.get_version()
    print(f"firmware_major: {firmware_major}; "
          f"firmware_minor: {firmware_minor}; "
          f"firmware_debug: {firmware_debug}; "
          f"hardware_major: {hardware_major}; "
          f"hardware_minor: {hardware_minor}; "
          f"protocol_major: {protocol_major}; "
          f"protocol_minor: {protocol_minor}; "
          f"padding: {padding}; "
          )


def test_device_reset1(sensor):
    sensor.device_reset()


def test_start_continuous_measurement1(sensor):
    sensor.start_continuous_measurement()
    (a_mass_concentration_pm1p0, a_mass_concentration_pm2p5, a_mass_concentration_pm4p0, a_mass_concentration_pm10p0,
     a_temperature, a_humidity, a_voc_index, a_nox_index, a_hcho
     ) = sensor.read_measured_values()
    print(f"a_mass_concentration_pm1p0: {a_mass_concentration_pm1p0}; "
          f"a_mass_concentration_pm2p5: {a_mass_concentration_pm2p5}; "
          f"a_mass_concentration_pm4p0: {a_mass_concentration_pm4p0}; "
          f"a_mass_concentration_pm10p0: {a_mass_concentration_pm10p0}; "
          f"a_temperature: {a_temperature}; "
          f"a_humidity: {a_humidity}; "
          f"a_voc_index: {a_voc_index}; "
          f"a_nox_index: {a_nox_index}; "
          f"a_hcho: {a_hcho}; "
          )
    (padding, data_ready
     ) = sensor.get_data_ready()
    print(f"padding: {padding}; "
          f"data_ready: {data_ready}; "
          )
    sensor.stop_measurement()

