#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# (c) Copyright 2023 Sensirion AG, Switzerland
#
#     THIS FILE IS AUTOMATICALLY GENERATED!
#
# Generator:     sensirion-driver-generator 0.32.0
# Product:       sen68
# Model-Version: 1.0.0
#

import argparse
import time
from sensirion_i2c_driver import LinuxI2cTransceiver, I2cConnection, CrcCalculator
from sensirion_driver_adapters.i2c_adapter.i2c_channel import I2cChannel
from sensirion_i2c_sen68.device import Sen68Device

parser = argparse.ArgumentParser()
parser.add_argument('--i2c-port', '-p', default='/dev/i2c-1')
args = parser.parse_args()

with LinuxI2cTransceiver(args.i2c_port) as i2c_transceiver:
    channel = I2cChannel(I2cConnection(i2c_transceiver),
                         slave_address=0x6B,
                         crc=CrcCalculator(8, 0x31, 0xff, 0x0))
    sensor = Sen68Device(channel)
    sensor.device_reset()
    time.sleep(1.2)
    serial_number = sensor.get_serial_number()
    print(f"serial_number: {serial_number}; "
          )
    sensor.start_continuous_measurement()
    for i in range(50):
        try:
            time.sleep(1.0)
            (a_mass_concentration_pm1p0, a_mass_concentration_pm2p5, a_mass_concentration_pm4p0, a_mass_concentration_pm10p0,
             a_temperature, a_humidity, a_voc_index, a_nox_index, a_hcho
             ) = sensor.read_measured_values()
            print(f"a_mass_concentration_pm1p0: {a_mass_concentration_pm1p0}; "
                  f"a_mass_concentration_pm2p5: {a_mass_concentration_pm2p5}; "
                  f"a_mass_concentration_pm4p0: {a_mass_concentration_pm4p0}; "
                  f"a_mass_concentration_pm10p0: {a_mass_concentration_pm10p0}; "
                  f"a_temperature: {a_temperature}; "
                  f"a_humidity: {a_humidity}; "
                  f"a_voc_index: {a_voc_index}; "
                  f"a_nox_index: {a_nox_index}; "
                  f"a_hcho: {a_hcho}; "
                  )
        except BaseException:
            continue
    sensor.stop_measurement()
